service: example

image: example

ssh:
  user: kamal

env:
  secret:
    - DJANGO_SECRET_KEY

proxy:
  ssl: true
  host: example.iwanalabs.com
  app_port: 8000
  healthcheck:
    path: /kamal/up/
    interval: 2
    timeout: 2

servers:
  web:
    - 128.140.0.209

accessories:
  redis:
    image: redis:7.0
    roles:
      - web
    cmd: --maxmemory 200m --maxmemory-policy allkeys-lru
    volumes:
      - /var/redis/data:/data/redis
    options:
      memory: 250m
      network: private_network

volumes:
  - "/db/:/app/db/"

registry:
  server: <account_id>.dkr.ecr.<region>.amazonaws.com
  username: AWS
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  dockerfile: "../Dockerfile"
  context: "../"
  cache:
    type: gha
